# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3ee7120f1d9907350ba2d4f00bcd5545a3913803ea8705d97cfb60ec0f8cc3779fb098247d9c1ba2f395a82e33202e454e8eb919f0f77b0db5a1809ab44220c

test:
  secret_key_base: c37f7105a64beb5c7c599d3529850e23dc810445c4f1cca9b891fc091e9f744b51aebd00e61986c8e5e02ddb204e296d4e17e266f5840e9e8c27a6268a963245

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
